server:
  compression:
    enabled: true
  port: 8080          # Default port
  shutdown: graceful  # Enable graceful shutdown

# Spring Configuration
spring:
  application:
    name: redis-cluster-app
  docker:
    compose:
      enabled: false # Only enabled when started with '-Dspring-boot.run.profiles=docker'

# Redis Configuration
redis:
  config:
    read-timeout: 1s
    max-idle-pool: 8
    max-total-pool: 8
    max-wait: 1s
    min-idle-pool: 0
    nodes:
      - 'localhost:7000'
      - 'localhost:7002'
      - 'localhost:7003'

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true