# Spring Boot Docker Configuration
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down

# Redis Configuration (Primary nodes, replicas are discovered)
redis:
  config:
    nodes:
      - 'localhost:7000'
      - 'localhost:7001'
      - 'localhost:7002'
