version: '2'
services:
  redis-cluster:
    container_name: redis-cluster
    hostname: redis-cluster
    image: grokzen/redis-cluster:6.0.7
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=7000
      - SLAVES_PER_MASTER=2
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "7007:7007"
      - "7008:7008"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis-cluster:redis-cluster:7000,redis-cluster:redis-cluster:7001, redis-cluster:redis-cluster:7002,redis-cluster:redis-cluster:7003,redis-cluster:redis-cluster:7004,redis-cluster:redis-cluster:7005,redis-cluster:redis-cluster:7006,redis-cluster:redis-cluster:7007,redis-cluster:redis-cluster:7008
    ports:
      - "8081:8081"
    depends_on:
      - redis-cluster

